---
title: "Academic Curriculum Vitae"
author: "`r format(Sys.time(), '%d %B, %Y')`"
date: "15/03/2021"
output: word_document
---

```{r setup, include=FALSE}
library(scholar)
library(knitr)
library(tidyverse)
library(janitor)
library(flextable)
opts_chunk$set(echo = FALSE)

id <- get_scholar_id(first_name = "Anthony", last_name = "Kimpton", affiliation = NA)

publications <- get_publications(id)

impact <- get_impactfactor(journals=publications$journal, max.distance = 0.1)

rank <- get_journalrank(journals=publications$journal)

table <- cbind(publications, impact, rank) %>%
  clean_names() %>% 
  mutate_if(is.factor, as.character) %>% 
  select(author, year, title, journal, number, sjr_best_quartile, cites, impact_factor, eigenfactor) %>% 
  arrange(desc(year))

#history_id <- get_citation_history(id)

#history_article <- get_article_cite_history(id, table[1,8])
```


```{r coauthors, eval=FALSE}
FUNCTION IS NOT WORKING
coauthor_network <- get_coauthors(id, n_coauthors = 5, n_deep = 1)
plot_coauthors(coauthor_network)
```

```{r, include=TRUE}
flextable(table) %>% 
  theme_vanilla()
```

