---
title: Summarised Academic Curriculum Vitae
author: Anthony Kimpton
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pagedown::html_resume:
    css: 
      - override.css         # OVERIDE CERTAIN FUNCTIONS OF CSS
      - resume               # DEFAULT FILE
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> [a.kimpton@uq.edu.au](a.kimpton@uq.edu.au)
- <i class="fa fa-github"></i> [https://github.com/akimpt](https://github.com/akimpt)
- <i class="fa fa-phone"></i> +61 412 452 471
- For more information, please contact me via email.

Main
================================================================================

Anthony Kimpton {#title}
--------------------------------------------------------------------------------

<h5><b>Response to Selection Criteria</b></h5>

### ESSENTIAL

### 1. Completion or near-completion of a doctoral qualification in a relevant field or equivalent accreditation and standing

My PhD conferral was in November, 2018 and I was awarded a University of Queensland (UQ) Dean's Award for Outstanding HDR Theses in August, 2020 for my PhD thesis entitled “The Sociability of Urban Greenspace: An Exploration of How Public Parks and Private Backyards Influence the Social Sustainability of Urban Communities”. Profs Rachel Armitage from the University of Huddersfield and Lex Comber from the University of Leeds were my thesis examiners and required no changes to my thesis and they respectively wrote: “I have examined 12 PhDs and supervised 8 to completion...this PhD is one of the strongest that I have read…flawless thesis which contributes to the field in terms of theory, methodology and policy/practical application…candidate should be congratulated for presenting such a complex topic in an accessible format that will be useful to both policy-makers and practitioners (as well as academics).” and “The novelty of the thesis lies in the consideration of both public and private spaces… providing a strong theoretical development in this field, as is the exploration of deeper bottom-up social dimensions related to greenspaces as different types of activity spaces and not just top down policy based ones.”

My thesis was grounded in social sustainability/resilience theory and explored how public greenspace social equity and residential preferences impact community social sustainability. My analysis drew upon land use policy, social surveys, remote imagery, public assets registers, cadastral data, census, and crime incidence data.

### 2. Planning Institute of Australia registration or the capacity to become registered as a Full Member of the Planning Institute of Australia.

I have an undergraduate degree in sociology, a doctorate in urban geography, and have published in planning journals thus I am eligible for membership to the Planning Institute of Australia and possibly further similar international professional institutes.

### 3. Effectiveness as a teacher, which is evidenced by:⋅ student feedback on teaching using valid instrument/s, peer review and/or student outcomes, and ⋅ the capacity to conceive, develop and deliver higher education curricula and contribute to relevant areas of teaching

I regard student feedback as invaluable for continual refinement of my teaching approach that started from 4.2 overall on 5-point scale during my 2nd year of PhD candidature—already high within my school—and has since risen to 4.5 for both online and face-to-face delivery of classes with close to 200 students. As such, my lecturer evaluations are rapidly approaching my earlier tutor evaluations at 4.7 overall on 5-point scale. It was because of these tutor evaluations and my tutorial workbooks and slides that I was hand-picked to redesign a capstone course for the urban planning and geography program. 

My overarching teaching approach is informed by my experience as a sociology undergraduate where lecturers valued student input. While I have taught within the School of Social Sciences, the majority of my teaching experience is within the School of Earth and Environmental Sciences (SEES; formerly School of Geography, Planning, and Environmental Management) within the UQ Science Faculty and home to the urban planning and geography disciplines. As such, it has been my delight to introduce science faculty students to a more participatory social sciences faculty approach to teaching. Notably, these students often arrive to classes with the expectation that they only need to listen for the answers to potential multiple-choice questions only to discover that they enjoy discussing course content while I can enjoy hearing my diverse cohorts of students interpret my course content through their own lived experiences. I also find this is an effective way of improving student engagement since it motivates students to stay on top of my assigned readings and videos—I am very fond of TED talks—as they wish to appear well-informed in front of their classmates, and I have immediate feedback as to whether they thoroughly understand the concepts before I progress any further and potentially overwhelm them with course content. Students have consistently indicated that they appreciate my student-centred approach to teaching through their teaching evaluations e.g., “…engaging and encouraged student input often…strongly encouraged participation and gave clear answers……enjoyed the quirky references Anthony used to explain some of the concepts…The memes/pop culture references were really engaging and relevant…provided engaged responses to queries and concerns when raised …. He answers our questions expands on course content in a logical manner so it becomes more understandable…excitement for the topic he was talking about made it more engaging…I really enjoyed learning about the social side of cities…talking speed was very good…slow and ensured that students comprehended concepts before moving on…very helpful and approachable as well. The classes always seemed to run smoothly and I always left fully understanding all content that we went over in the class …he had a great attitude to what he was teaching which made the lectures more enjoyable…”

### 4. Evidence of research experience, including for example, refereed publications; participation in research teams; co-supervision of candidates for honours and higher degrees by research.

My research outputs concentrate on developing interdisciplinary conceptual models, strengthening operationalisations, and employing spatial modelling approaches to examine the social impacts of land use and transport policies. I am currently drafting a DECRA application so am able to provide a quick, clear sense of my current research impact. In my short research career, I have 15 peer-reviewed publications which includes 4 sole-authored articles, 1 lead-authored monograph, 1 lead-authored book chapter, 4 lead-authored articles, 5 co-authored articles, and 2 co-authored book chapters. At the time of writing, I have 199 citations and a h-index of 6 ([Google Scholar 15/12/21](https://scholar.google.com/citations?user=rq0D3PMAAAAJ&hl=en)) and my academic productivity exceeds the 14 median for Australian urban planning Level Bs and my citation count exceeds the 167 median for our Level Cs ([Pojani et al. 2018](https://journals.sagepub.com/doi/10.1177/0739456X18804330)). Likewise, my research productivity exceeds the average human geographer from the United States or Canada with 6-15 career years that publish 1.4 articles and gain 13.8 cites annually, and I exceed the entire geography discipline that has 159.10 cites in total and a 5.7 h-index ([Coomes et al. 2013](https://www.tandfonline.com/doi/pdf/10.1080/00330124.2012.697798)).

I have publications in leading journals across multiple intersecting academic disciplines including geography, urban studies, urban planning, and social psychology. These include: *Applied Geography* (impact factor = 1.17; 57/777 Geography, Planning & Development); *Progress in Planning* (impact factor = 1.50; 38/777 Geography, Planning & Development); *Land Use Policy* (impact factor = 1.67; 26/777 Geography, Planning & Development; 27/389 Management, Monitoring, Policy and Law; 10/178 Nature and Landscape Conservation); *Environment and Planning A: Economy and Space* (impact factor = 1.74; 20/777 Geography, Planning, & Development); *Journal of Research in Crime and Delinquency* (impact factor = 1.93; 16/308 Social Psychology); *Urban Studies* (impact factor = 1.92; 5/256 Urban Studies); and *Globalization and Health* (impact factor = 1.47; 56/560 Public Health, Environmental and Occupational Health; 21/256 Health Policy) amongst others (SciMago 15/12/21).

Scopus has identified 6 of my journal articles and reports that 2 are international collaborations and 3 are ranked within the top 10% most impactful publications worldwide and this is irrespective of research field (SciVal 3/12/21). Specifically, my research impact for “Greenspace; Green Infrastructure; Cultural Ecosystem Services” exceeds the field by a factor of 2.62 and is located at the 99.83 percentile for my contributions towards understanding social equity and planning policy. In “Crime Prevention; Policing; Environmental Design” my impact exceeds the field by a factor of 2.99 and is located at the 97.52 percentile, which highlights my capacity for theorising and examining how the built and natural environment influence social behaviour. Lastly for research field, my “Travel Behavior; Mode Choice; Urban Form” impact exceeds the field by a factor of 2.44 and is located at the 98.62 percentile in a field predominantly comprising large civil engineering teams employing traffic simulations and choice models, and my “Park and Ride; Parking; Traffic Congestion” research impact exceeds the field by a factor of 2.09 and is located at the 75.46 percentile although these are relatively recent publications.

Web of Science has identified 10 articles and 1 monograph and so provides a broader sense of my research impact by discipline (InCites 3/12/21). For example, my research impact within “Geography” exceeds the discipline by a factor of 4.25 and is located at the 96.09 percentile, which highlights my capacity for spatial reasoning and analyses. Further, my “Public, Environment, & Occupation Health” exceeds the discipline by 4.55 and is located at the 94.04 percentile, which highlights that my geographical research impact extends into adjacent disciplines. Likewise, it extends into my “Criminology & Penology” where I exceed the discipline by a factor of 1.74 and I am ranked at the 80.75 percentile for this discipline with just a handful of discipline-specific publications, and my “Environmental Studies” exceeds this discipline by 1.62 and is at the 80.36 percentile for a discipline that primarily focusses on environmental and economic indicators rather than social indicators.

While this is potentially answering beyond the criteria, I would like to highlight that I was also recently awarded a $89,342 Australian Urban Research Infrastructure Network (AURIN) High Impact Projects Grant with CIs in urban planning from UQ, RMIT, and the University of Leeds. We are developing the Green Australian Vehicle Ownership (GreenAVO) service that links state vehicle registrations and the federal Green Vehicle Guide APIs for examining transport disadvantage and the emergence of electric vehicles at the postcode level. This service can reveal the extent of household burdens such as auto dependency and the “drive till you qualify problem”, aid fairer recalibration of fuel excise taxes, and accelerate the national transition towards electric vehicles for greener mobility and energy security for Australia. My intent it to target similar grants as these are becoming more commonplace such as developing services that gather, harmonise, and expose important social data (e.g., ABS data products, crime incidence, cadastre, policy zoning, and public assets and infrastructure) to researchers via APIs to minimise the “cold starts” at the start of new projects.

In sum, my research contributions exceed the career average for both urban planners and human geographers at later career stages. I attribute my interdisciplinary publishing success both to my open science approach entailing sharing scripts and methodological appendices for research transparency, and to my general focus on conceptual models, policy analysis, operationalisation, and classification that are portable to other studies. It is also important to highlight that my 2021 software developer appointment within the UQ School of Civil Engineering in collaboration with the Australian Urban Research Infrastructure Network and four other Australian Civil Engineering Schools has reduced my opportunity to prioritise research publications however research output continues to exceed my academic seniors in both urban planning and geography as I gain service development expertise. 

I am formally supervising an interdisciplinary PhD candidate (i.e., urban planning and civil engineering), and will be supervising a demography PhD in 2022 as they return from maternity leave. I also have ample experience with supervising RhDs in an informal capacity which started in 2013 when I began tutoring statistics to RhDs prior to commencing my own PhD candidature and continued to help these students where I could throughout their candidatures. 

### 5. Membership of and sound connections with relevant professional bodies and community groups and/or in professional practice.

As noted in response to criteria 2, I am not currently a PIA member although I participate in some events such as Keeble Lectures and recently attended PIA Awards of Excellence Gala Dinner as an award nominee. I am however a full member of both the Institute of Australian Geographers and the International Geographical Union.

Further, my PhD project involved collaboration with 5 Greater Brisbane local governments, my first two years as a postdoctoral research fellow was on an Australian Research Council Discovery Project partnered with the Department of Transport and Main Roads, and my 2021 appointment is managed through weekly meetings with AURIN and quarterly meetings with members of the National Cloud Research Infrastructure Network (NCRIS), the Australian Bureau of Statistics, and research end user representatives from state government and universities. 

I am also deeply committed to public engagement, and my research outputs and activities have also meant that I am beginning to develop a public profile. For instance, I have organised a public forum and round table discussion event in West End that was attended by over 100 residents, traders, and civil servants to discuss whether Boundary St on-street parking should be replaced with protected bike lanes. As a result, I was later invited to Councillor Jonathan Sri’s office to discuss my greenspace research. Likewise, I have co-authored three articles for the Conversation that are attracting considerable public attention (i.e., 269 comments and 56,284 reads) and resulted in being invited to the offices and events of professional organisations (e.g., Urban Land Institute), engineering and architectural firms (e.g., WSP and BlightRayner), and to discuss my research with national campaigners and broadcasters (e.g., 202020 Vision, Channel Nine News, and recently The Drum on the ABC ran a segment on my research). 

### 6. Strong personal qualities and collegial approaches that contribute to the development and maintenance of a positive academic environment which is conducive to high levels of engagement and standards of achievement for both staff and students.

I have been and continue to be a founding member of interdisciplinary and transdisciplinary urban research networks e.g., the University of Queensland’s Housing And Urban Society (UQ-HAUS) and the City Science Transdisciplinary Impact Research Network (TIRN). Further, I have been the UQ  Early Career Researcher committee representative for The Australian Sociological Association (TASA), and was invited and accepted roles such as the urban planning representative on the SEES RhD Committee, and the EMCR representative on the Science Faculty’s Research committee. Even prior to this point in my career, I was selected amongst my PhD candidature peers to be the SEES representative where I was paid to develop and deliver presentations at high schools and teacher’s conferences with the aim of persuading high school students to consider careers in geographical science, urban planning, environmental management, and geology.

### 7. Evidence of participation in academic development activities and the desire to continue to learn and improve as an effective academic.

I place a high priority on my continued and self-directed professional development since I regard this as an obligation for scientists that intend to remain at the top of their profession. As detailed in my attached academic CV under “Other Skills and Qualifications”, I am a regular participant at programming, writing, and industry engagement workshops but what is not highlighted is that I am also someone that participates in hack-a-thons, attends and organises Meetup.com events, and I am also often the organiser for university-based ECR workshops. In addition, I would also like to highlight that I have university training in Stata and bootcamp training in Python but I am a purely self-taught yet advanced R user so I can demonstrate that I am highly motivated and adept at self-directed learning and am regularly told by colleagues that this is one of my key strengths and stand-out traits as a researcher.

### DESIRABLE

### 8. Experience in design and delivery of curricula in planning and environmental policy, strategy, legislation (and application to plan-making and development assessment), regulation, Court and appeals.

I have publications that focus on environmental policy, strategy, legislation, and regulation although not court and appeals as my focus is typically conceptual models and evaluating policy impact e.g.,   

* Kimpton, A., Pojani, D., Ryan, C., Ouyang, L., Sipe, N., & Corcoran, J. (2021). Contemporary parking policy, practice, and outcomes in three large Australian cities. Progress in Planning, 100506. https://doi.org/10.1016/j.progress.2020.100506 
* Kimpton, A. (2017). A spatial analytic approach for classifying greenspace and comparing greenspace social equity. Applied Geography, 82, 129–142. https://doi.org/10.1016/j.apgeog.2017.03.016 

This and similar material feature heavily in my design and delivery of curricula. This includes my 6 sustainability, garden cities, and new mobilities lectures developed for the GEOG3000: The Global Metropolis course, and my education, health, and retail service delivery lectures for GEOG1000: Human Settlements. Please note that although these have “GEOG” course codes, these have been mandatory capstone and introductory urban planning program courses throughout most of my lecturing experience.   

### 9. Experience in design and delivery of curricula in community engagement and conflict resolution and its application in planning settings such as social policy, social impact assessment, community resilience, place-making, ethics, inclusive of diverse populations of Aboriginal and Torres Strait Islanders, people with disabilities, children and older people.

As noted, I was awarded the UQ Dean’s Award for Outstanding Thesis for developing the first social sustainability index so I am exceptionally well-versed in social impact assessments. I am currently drafting a transport disadvantage DECRA application that draws focus on the mobility needs of people with disabilities, the elderly, mothers, single parents, and people with carer responsibilities. Moreover, I currently have a manuscript investigating how the 2011 Brisbane Floods impacted community resilience that is under review for the American Journal of Community Psychology and my publications overall focus heavily on how the built and natural environment impacts community sociability and behaviour e.g.,

* Kimpton, A., Wickes, R., & Corcoran, J. (2014). Greenspace and place attachment: Do greener suburbs lead to greater residential place attachment? Urban Policy and Research, 32(4), 1–21. https://doi.org/10.1080/08111146.2014.908769
* Kimpton, A., Pojani, D., Sipe, N., & Corcoran, J. (2020). Parking Behavior: Park ‘n’ Ride (PnR) to encourage multimodalism in Brisbane. Land Use Policy, 0. https://doi.org/10.1016/J.LANDUSEPOL.2019.104304
* Zahnow, R., Corcoran, J., Kimpton, A., & Wickes, R. (2021). Neighbourhood places, collective efficacy and crime: A longitudinal perspective. Urban Studies. https://doi.org/10.1177/00420980211008820
* Kimpton, A. (2020). Explaining the Railheading Travel Behaviour with Home Location, Park “N” Ride Characteristics, and the Built Environment to Strengthen Multimodalism. https://doi.org/10.1007/s12061-020-09361-4
* Corcoran, J., Zahnow, R., Kimpton, A., & Wickes, R. (n.d.). The temporality of place: Constructing a temporal typology of crime in commercial precincts. 48(1), 9–24. https://doi.org/10.1177/2399808319846904.
* Sigler, T., Mahmuda, S., Kimpton, A., Loginova, J., Wohland, P., Charles-Edwards, E., & Corcoran, J. (2021). The socio-spatial determinants of COVID-19 diffusion: the impact of globalisation, settlement characteristics and population. Globalization and Health, 17(1), 1–14.
* Sigler, T., Boyd, H., & Kimpton, A. (2021). Sociospatial Factors Explaining Daylight Saving Preferences in Australia. The Professional Geographer, 73(4), 765–774.

This material features heavily within some the previously listed lectures including the garden cities, new mobilities, and community lectures developed for the GEOG3000: The Global Metropolis, and the education and health service delivery lectures for GEOG1000: Human Settlements.

### 10. Research experience in areas focusing on planning and environmental policy, strategy, legislation; or community engagement, resilience, social policy, inclusiveness of diverse populations; or criminology and justice as it relates to the management and design of cities and towns.

My four years as a part-time research assistant on a criminological ARC Discovery Project has afforded three separate occasions to present Crime Prevention Through Environmental Design (CPTED) research at the American Society of Criminology conference. This is the highest attended Criminology conference worldwide and has been an exceptional opportunity to develop an international research network in environmental criminology. Further, Prof Rebecca Wickes was one of my PhD supervisors and Prof Rachel Armitage was one of my thesis examiners that are both world-leading environmental criminologists. Further, my highest cited and sole-authored publication is on social equity and inclusion as is my current DECRA application. Having already highlighted that my research impact in both these fields is above the 97th percentile, I will now draw attention to the more representative and already accepted publications e.g.,  

* Kimpton, A. (2017). A spatial analytic approach for classifying greenspace and comparing greenspace social equity. Applied Geography, 82, 129–142. https://doi.org/10.1016/j.apgeog.2017.03.016 
* Kimpton, A., Corcoran, J., & Wickes, R. (2017). Greenspace and crime: An analysis of greenspace types, neighboring composition, and the temporal dimensions of crime. Journal of Research in Crime and Delinquency, 54(3), 303–337. https://doi.org/10.1177/0022427816666309 
* Corcoran, J., Zahnow, R., Kimpton, A., & Wickes, R. (n.d.). The temporality of place: Constructing a temporal typology of crime in commercial precincts. 48(1), 9–24. https://doi.org/10.1177/2399808319846904

The ideas within these publications are central to both my garden cities and community lectures developed for the GEOG3000: The Global Metropolis course.

### 11. Experience undertaking academic administrative functions, e.g. course coordination, within a University

I have not undertaken course coordination roles so far as SEES typically reserves these responsibilities for continuing academics however I have had multiple high-profile committee roles as noted previously and I was the lead tutor for GEOG1000: Human Settlements for four years responsible for two to four tutors for class sizes of up to 200 first year students. It also included multiple administrative functions including assessment development and moderation and as noted, this was a compulsory introductory course for the Bachelor of Urban and Regional Planning.
