---
title: "Anthony Kimpton's resume"
author: Anthony Kimpton
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> a.kimpton@uq.edu.au
- <i class="fa fa-github"></i> [https://github.com/akimpt](https://github.com/akimpt)
- <i class="fa fa-phone"></i> +61 412 452 471
- For more information, please contact me via email.

Skills {#skills}
--------------------------------------------------------------------------------

- geospatial, temporal, and textual statistical analysis of big data for explanatory models, machine learning for classification, variable selection, and regularization for predictive models

- highly skilled in R (programming language), Stata, ArcGIS, Python, and SQL and familiar with Bash, Docker, HTML, and CSS, and employ advanced rMarkdown workflow for generating manuscripts, reports, presentations, APIs, static and interactive web pages and applications, and resumes...I would like to acknowledge the developers of R's [*scholar*](https://cran.r-project.org/web/packages/scholar/index.html) and [*pagedown*](https://github.com/rstudio/pagedown) packages for streamlining my resume updating and drafting. The version you are reading was last updated on `r Sys.Date()`.

Main
================================================================================

Anthony Kimpton {#title}
--------------------------------------------------------------------------------

### Seeking Teaching and Research Position

I am seeking a *teaching research position* and am **well-suited** because blah blah.

[https://towardsdatascience.com/create-your-resume-with-pagedown-package-in-r-123ca6310d52](https://towardsdatascience.com/create-your-resume-with-pagedown-package-in-r-123ca6310d52) is the guide for this resume template

[https://api.emsidata.com/apis/skills](https://api.emsidata.com/apis/skills) is an api for keywords and ranked importance

[https://fontawesome.com/](https://fontawesome.com/) for icons

[https://resumeworded.com/results-v2](https://resumeworded.com/results-v2) and [https://www.jobscan.co/results/16564079](https://www.jobscan.co/results/16564079) for testing your resume

For elaboration or clarification on any of my experience, skills, or career aims, please feel free to contact me.

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Doctor of Philosophy

The University of Queensland’s School of Earth and Environmental Sciences

Brisbane, Australia

2018

**Thesis**: The Sociability of Urban Greenspace: An Exploration of How Public Parks and Private Backyards Influence the Social Sustainability of Urban Communities

**Focus**: developing the first quantitative social sustainability measure, and employing social survey, crime incidence, remote imagery, administrative, and population census data to examine how public greenspace and backyards influence the neighborhood social sustainability

**Geography & Sociology**: logistic, negative binomial, and linear regression, cluster analysis using Stata 

### 1st class Bachelor of Arts Honours

The University of Queensland’s School of Social Sciences

Brisbane, Australia

2012

**Thesis**: Seeing Green: Can the Objective Physical Environment Predict Place Attachment? employing social survey, crime incident, census, and administrative data to examine how public greenspace influences place attachment   

**Sociology**: multi-level statistical modelling; research design and scoping

### Bachelor of Arts

The University of Queensland’s School of Social Sciences

Brisbane, Australia

2011

**Sociology & Archaeology**: statistical modelling using Stata and Excel; qualitative interviewing methods; geo-spatial analysis or GIS  using ArcGIS; field work; laboratory methods and procedures

Grants and Awards {data-icon=trophy}
--------------------------------------------------------------------------------

### $89,342 High Impact Projects Grant 

The Australian Urban Research Infrastructure Network

Melbourne, Australia

2021

**Aim**: lead the development of the Green Australian Vehicle Ownership (GreenAVO) service that harvests and links Australian state and territory vehicle registration APIs with vehicle characteristics from the Australian Green Vehicle Guide API to reveal spatio-temporal trends in vehicle ownership at the postcode-level for tracking, predicting, and accelerating the national transition towards hybrid and electric vehicles through strategic planning and infrastructure.

### Dean's Award for Outstanding HDR Thesis

The University of Queensland’s Graduate School

Brisbane, Australia

2020

**Criteria**: both thesis examiners: Professors Alexis Comber and Kate Bowers describing the 2018 thesis is an outstanding theoretical, empirical, and applied research contributions requiring no changes.




2020	The Institute of Australian Geographers’ Travel Grant
Awarded $1,000 to present at the International Geographical Union Congress in Istanbul that has been postponed until national travel restrictions are lifted.
2019	The School of Earth and Environmental Sciences’ Early Career Researcher Grant	
Awarded $1,210 to attend the 2019 Australian Sociological Association Conference
2013	The Australian Research Council’s Australian Post Graduate Award 
Awarded $24,653 per annum throughout my PhD candidature


Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Postdoctoral Research Fellow

The Australian Urban Research Infrastructure Network and the University of Queensland’s School of Civil Engineering 

Brisbane, Australia

2021

**Role**: develop microservices (AGILE software development) for the Australian Transport Research Cloud e.g, interactive graphics and dashboards, and application programming interfaces (API) for the public and collaborating universities using R (programming language), Docker for containerisation, and Bash for AURIN Virtual Machine opperations   

### Postdoctoral Research Fellow

The Queensland Department of Transport and Main Roads & The University of Queensland’s School of Earth and Environmental Sciences 

Brisbane, Australia

2018 - 2020

**Role**: review Australian land use and transport policy, examine land use and census data to determine how parking supply aligns with policy influences urban mobility using the R (programming language) for all GIS, statistical modeling, and reporting including the [project page](https://parks-uq.github.io/)  

### Research Assitant

The University of Queensland’s School of Geography, Planning, and Environmental Management 

Brisbane, Australia

2013-2018

**Role**: review community sociology and environmental criminology research literature focusing on how natural disasters impact community sociability, and examine social survey, crime incident, census, flood, and administrative data using ArcGIS for spatial analyses and cartography, and Stata for statistical modelling and data visualization

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### PhD Supervisor 

The University of Queensland’s School of Civil Engineering & School of Earth and Environmental Sciences 

Brisbane, Australia

2021 - present

Supervising one PhD candidate investigating the First and Last Mile Problem of public transport and further investigating internal migration of immigrants within Australia

### Sessional Lecturer 

The University of Queensland’s School of Earth and Environmental Sciences 

Brisbane, Australia

2016 - present

**Teaching Evaluations**: ranging 4.1 to 4.3 on a 5-point scale with 4.3 most recently awarded for both online and face-to-face delivery 

::: concise
- **GEOG1000: Human Settlements**: develop and present lectures on the history of human settlements and future of cities to over 200 first-year urban planning, geography, and environmental management students per semester
- **GEOG2202/GEOG7202: Global Population Issues**: develop and deliver lectures on global demographic challenges to over 60 second-year and postgraduate urban planning and geography students per semester
- **GEOG3003: The Global Metropolis**: invited for first lecturing assignment to revamp and re-badge the “GEOG3030: the Asian Metropolis” capstone course by developing and delivering six new lectures on topics including smart cities, transport, and sustainability to over 40 final-year urban planning and geography students per semester
:::

### School Representative

The University of Queensland’s School of Earth and Environmental Sciences 

Brisbane, Australia

2016 - 2017

**Role**: invited and employed to develop and deliver presentations at high schools, career open days, and high school teaching conferences to promote geography, planning, environmental management, and geology

### Lead Tutor/Demonstrator 

The University of Queensland’s School of Earth and Environmental Sciences & School of Social Sciences

Brisbane, Australia

2013 - 2018

**Teaching Evaluations**: ending with 4.7 on a 5-point scale for face-to-face delivery and consistently high evaluations created opportunities to lecture    

::: concise
- **GEOG1000: Human Settlements**: develop practicals, workbooks, and assessments for over 200 first-year geography, environmental management, and urban planning students per semester, and manage and train up to 4 demonstrators running a portion of these practicals per semester
- **SOCY2339/7339: Introduction to Quantitative Methods**: develop and deliver introductory statistical modelling workshops using Stata for over 60 second-year and 20 research by higher degree students per semester
- **SOCY2340: Sociology of the City**: tutor across urban topics including public space, social equity, community sociability, and environmental criminology to over 60 second-year sociology, criminology, urban planning, and geography students per semester
- **CRIM1000: Introduction to Criminology** develop and deliver introductory criminology tutorials to over 60 first-year criminology students per semester
:::

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### The Early- and Mid-Career Researcher Representative

The University of Queensland’s Faculty of Science Research Committee

Brisbane, Australia

2019 - 2020

**Role**: invited to represent EMCRs at monthly faculty research committee meetings chaired by the faculty Associate Dean of Research

### The Urban Planning and Geography Representative

The University of Queensland’s School of Earth and Environmental Sciences Early Career Researcher Committee

Brisbane, Australia

2019 - 2020

**Role**: invited to represent urban planning and geography ECRs at monthly school meetings, and develop grant guidelines and applications, evaluate these applications

### Milestone and Thesis Examiner

N/A

N/A

2018 - present

**Role**: examine RhD milestones and theses on topics including environmental criminology, urban sociology, demography, land use and transport planning, and urban ecology 

### Academic Journal Reviewer

N/A

N/A

2015 - present

**Role**: peer-review for journals including: Applied Geography; Applied Spatial Analysis and Policy; Australian Planner; Behavioural Research Methods; City, Culture and Society; Ecosystem Services; Environment and Behaviour; Environment and Planning B: Urban Analytics and City Science; Environmental Planning and Management; Geoforum; Housing and the Built Environment; Land Use Policy; Landscape and Urban Planning; Landscape Research; Population Research; Research in Crime and Delinquency; Security Journal; Social Science Research; Spatial Science; Springer Nature: Social Science; Sustainability; Sustainable Cities and Society; Transport Reviews; Travel Behaviour and Society; Urban Studies; and Urbanism: International Research on Placemaking and Urban Sustainability

Research Publications {data-icon=file}
--------------------------------------------------------------------------------

### Genetic and epigenetic signals are found predictive to the distribution of intra-individual divergence of alternative splicing.

Poster for 2013 International Conference of Genomics

Qingdao, China

2014

**Yu L**, Chen B, Zhang Z.

### ESCRT-0 complex modulates Rbf mutant cell survival by regulating Rhomboid endosomal trafficking and EGFR signaling.

J Cell Sci. 2016 May 15;129(10):2075-84.

N/A

2016 

Sheng Z, **Yu L**, Zhang T, Pei X, Li X, Zhang Z and Du W. 

Zahnow, R., Corcoran, J., Kimpton, A., & Wickes, R. (2021). “Neighbourhood places, collective efficacy and crime: A longitudinal perspective”. Urban Studies. https://doi.org/10.1177/00420980211008820 (SJR = Q1; Impact Factor = 1.92).
Sigler, T., Boyd, H. & Kimpton, A., (2021). “Socio-Spatial Factors Explaining Daylight Saving Preferences in Australia”. The Professional Geographer 1-10 (SJR = Q1; Impact Factor = 1.623).
Kimpton, A., Pojani, D., Sipe, N., & Corcoran, J. (2021) “Parking policy and bay-sharing for unmooring automobility from cities”. In T. Sigler & J. Corcoran (eds.) The Modern Guide to the Urban Sharing Economy 87-102. Edward Elgar Publishing.
Sigler, T., Mahmuda, S., Kimpton, A., Loginova, J., Wohland-Jakhar, P., Charles-Edwards, E., Corcoran, J. (2021) “The Socio-Spatial Determinants of COVID-19 Diffusion: The Impact of Globalisation, Settlement Characteristics and Population”. Globalization and Health 17 (1), 1-140. (SJR = Q1; Impact Factor = 2.65; Cites = 12).
Kimpton, A., (2020) “Explaining the railheading travel behaviour with home location, park ‘n’ ride characteristics, and the built environment to strengthen multimodalism”. Applied Spatial Analysis and Policy, 1-22. (SJR = Q2; Impact Factor = 1.367).
Kimpton, A., Pojani, D., Ryan, C., Ouyang, L., Sipe, N., & Corcoran, J. (2020) “Contemporary parking policy, practice, and outcomes in three large Australian cities”. Progress in Planning, 100506. (SJR = Q1; Impact Factor = 3.813; Cites = 5).
Kimpton, A. (2020) “Visualising Australia’s older population using grid maps”. Australian Population Studies, 4 (1), 70-72.
Kimpton, A., Pojani, D., Sipe, N., & Corcoran, J. (2020) “Parking behavior: park ‘n’ ride to encourage multimodalism in Brisbane”. Land Use Policy, 91: 104304 (SJR = Q1; Impact Factor = 3.194; Cites = 16).
Pojani, D., Kimpton, A., Sipe, N., Corcoran, J., Mateo-Babiano, I., & Stead D., (2019) “Setting the agenda for parking research in other cities”. In Parking: An International Perspective 245–260. Elsevier Inc: Amsterdam.
Kimpton, A. (2019) “Upset diagrams for examining whether parking maximums influence modal choice and car holdings”. Environment and Planning A: Economy and Space 52 (6), 1023-1026. (SJR = Q1; Impact Factor = 3.033).
Corcoran, J., Zahnow, R., Kimpton, A., Wickes, R., & Brunsdon, C., (2019) “The temporality of place: constructing a temporal typology of crime in commercial precincts”. Environment and Planning B: Urban Analytics and City Science 2399808319846904. (SJR = Q1; Impact Factor = 2.046; Cites = 6).
Pojani, D., Kimpton, A., & Rocco, R. (2019) “Planning students’ conceptions of research”. Journal of Planning Education and Research, 1-14. (SJR = Q1; Impact Factor = 1.260; Cites = 3).
Kimpton A. (2017) “A spatial analytic approach for classifying greenspace and comparing greenspace social equity”. Applied Geography 82: 129-142. (SJR = Q1; Impact Factor = 3.117; Cites = 52).
Kimpton, A., Corcoran, J., & Wickes R. (2016) “Greenspace and crime: an analysis of greenspace types, neighboring composition and the temporal dimensions of crime”. Journal of Research in Crime and Delinquency 54(3): 303-337. (SJR = Q1; Impact Factor = 2.899; Cites = 46). 
Kimpton, A., Corcoran, J., & Wickes, R. (2015) “Public greenspaces and crime: an analysis of crime timing and public greenspace amenities”. State of Australian Cities Conference Proceedings.
Kimpton, A., Wickes, R. & Corcoran, J. (2014) “Public greenspace and urban communities: do greener suburbs lead to greater residential place attachment?” Journal of Urban Policy and Research 32(4): 477-497. (SJR = Q1; Impact Factor = 1.286; Cites = 29).

Further Position-Relevant Training {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

2020	Asymmetric Innovations Industry Engagement Program
The University of Queensland’s Faculty of Science
2019	Writing for The Conversation	
The University of Queensland
2019	Science Communication and Mainstream Media
The University of Queensland’s Faculty of Science
2019	Alternate Futures Industry Engagement Program
The University of Queensland’s Faculty of Science
2017	Software Carpentry with Python
The University of Queensland’s Faculty of Engineering, Architecture and Information Technology
2016	Complete Python Bootcamp
Udemy	
2016	Stata Programming Workshop
The University of Queensland’s Institute of Social Science Research
2015	Multilevel Modelling Course
The University of Bristol’s Centre for Multilevel Modelling (hosted by the Queensland University of Technology)  	
2014	Open Knowledge Brisbane Data Visualisation Workshop
The Queensland State Library’s The Edge
2013	Envirohack Workshop
The Queensland State Library’s The Edge
2013	Tutors@UQ Program
The University of Queensland’s Faculty of Behavioural and Social Science

The Institute of Australian Geographers
The International Geographical Union

Professional Membership  {data-icon=phone}
--------------------------------------------------------------------------------

Referees  {data-icon=phone}
--------------------------------------------------------------------------------

### Professor Rebecca Wickes,

Director for the Monash Migration and Inclusion Centre

N/A

N/A

**Mail**: School of Social Sciences, Monash University, Clayton, Victoria, Australia,  3800

**Phone**: (+61) 413 623 929

**Email**: [rebecca.wickes@monash.edu.au](rebecca.wickes@monash.edu.au)

### Professor Jonathan Corcoran

Director of the Queensland Centre for Population Research

N/A

N/A

**Mail**: Room 512, Level 5, Chamberlain Building (#35), University of Queensland, St Lucia, Queensland, Australian, 4067

**Phone**: (+61 7) 336 56517

**Email**: [jj.corcoran@uq.edu.au](jj.corcoran@uq.edu.au)

### Emeritus Professor Neil Sipe

Former School Head of Urban and Regional Planning

N/A

N/A

**Mail**: Chamberlain Building (#35), University of Queensland, St Lucia, Queensland, Australian, 4067

**Phone**: (+61) 439 746 123

**Email**: [n.sipe@uq.edu.au](n.sipe@uq.edu.au)
